title: jichang portfolio
name: JICHANG LEE
email: jccc23@naver.com
description: >-
  Web Developer & Java Backend 


baseurl: ""
url: "https://jichang-lee.github.io"


# profile 이미지
profile_image: images/jichang.jpg



# Custom Color
primary: 0B0719 #메인 폰트 컬러 
primary_hover: 44A4F2 #메인 버튼색 
color_1: CF94D8 #bar1
color_2: CF94D8 #bar2
color_3: CF94D8 #bar3
color_4: CF94D8 #bar4 
color_5: CF94D8
color_6: CF94D8



# About
about_meta: About Me
about_header: >- 
  "Just do it and take it"
#about_introduce: >-
  
about_content: >-
  새로운 것에 도전하고 탐구하는 것을 즐깁니다. <br>
  컴퓨터에 호기심이 많았던 저는 컴퓨터공학과로 진학하여 IT기초 소양을 다졌습니다. 이후 IT기술과 경영의 융합 가치에 관심을 가지고 경영정보시스템(MIS)수업을 들으며 실제 기업경영에서 
  IT기술이 어떤식으로 적용되는지 배웠습니다. 또한 개발동아리 활동을 병행하며 기술력, 그 이상의 잠재력을 가진 개발자가 되고자 부단히 노력해왔습니다.
  첫 직장에서는 개발 기획 업무를 맡아 개발자의 상대 입장이 되어 안목을 넓혔고, 더 큰 세상을 경험하고자 퇴사 후 아일랜드로 떠나 학업과 일을 병행하며 새로운 삶을 살아보기도 했습니다. <br>
  <strong>이처럼 늘 새로운 것에 도전하고 적응해내어 목표를 달성하는 저의 성향은 급변하는 IT환경에 잘 적응하고 도전을 멈추지 않는 개발자로 성장할 수 있는 원천이 될 것입니다. </strong><br>
  이제는 다양한 경험을 토대로 제 분야에서 전문가가 되고자 합니다. 이를 위해 최근 총 6개월간의 NCS JAVA Spring 웹개발 교육과정 동안 성실하게 임하며 Spring framework를 활용한 웹사이트 개발을 완료하고, 목표를 달성하였습니다. 그 결과물을 포트폴리오로 첨부합니다. <br>
  

about_services: # 형식에 맞추어 항목 추가
- icon: icon-code
  name: Java
- icon: icon-data
  name: DB
- icon: icon-monitor
  name: Web
- icon: icon-phone3
  name: App

##about_box_content: 괜찮은 문구 <br>박스 색바꾸는 yml파일에 추가 <br><br><br>야물파일로 변환 <strong>의뢰</strong>의뢰
##about_box_button:
##  link: #
##  name: sample


# Tech  skill
tech_meta: TECH SKILLS
tech_header: "The Skills that I can do"
tech_content: 저는 이런 것을 할 수 있습니다. 
tech_list: # 형식에 맞추어 항목 추가
- name: JAVA
  color: color-1
  animation: fadeInLeft
  percent: 60
  mark: 60
  content: JAVA 기초와 객제 지향 언어의 기본적인 문법 & 자료구조 및 알고리즘을 자바로 공부하고있습니다.
- name: Spring Framwork
  color: color-2
  animation: fadeInRight
  percent: 60
  mark: 60
  content: Spring Boot 웹 프로젝트 경험으로 Spring framework의 전반적인 구조에 대해서 이해하고 있습니다.
- name: AWS
  color: color-3
  animation: fadeInLeft
  percent: 20
  mark: 20
  content: AWS EC2를 사용하여 자동화 배포를 한 경험이 있습니다. 
- name: Github
  color: color-4
  animation: fadeInRight
  percent: 30
  mark: 30
  content: 대부분의 프로젝트를 github를 통해 소스 코드를 관리하였으며, 인턴 생활 협업 역시 github을 통해 진행하였습니다. 또한 github서버를 활용하여 포트폴리오 사이트를 관리합니다.
tech_desc: 이 외 인턴 활동 당시<strong> javascript, vue.js</strong> 등을 배워가며 공부했습니다.<br>현재는<strong> Java & Spring Framework</strong> 의 기초를 좀 더 가꾸고 있습니다.


# Project
project_meta: My Work
project_header: PROJECT
project_introduce: 
#project_load_more: 앞으로 더 많은 프로젝트가 추가될 예정입니다.    # 더보기 내용
project_load_more_url: #
project_my_name: 개인 프로젝트

project_my: # 형식에 맞추어 항목 추가
# - background_url: images/spring.png
#   animation: fadeInLeft
#   name: Spring WEB site
#   description: Spring Framework를 활용한 웹사이트 제작 프로젝트 입니다.
#   detail_url: #
#   readmore_url: #

- background_url: images/gitblog.png
  animation: fadeInLeft
  name: DEV blog
  description: 깃 블로그를 직접 개발하여 배운 것들을 꾸준히 기록하며 배움을 나눕니다. 
  detail_url: https://hyesue-lee.github.io/
  readmore_url: #

project_team_name: 팀 프로젝트
project_team: # 형식에 맞추어 항목 추가
- background_url: images/personal_project1.PNG
  animation: fadeInRight
  name: Groupware(2022.04)
  description: 동네 지구대에서 쓸법한 프로젝트입니다. 공유 게시판 및 캘린더를 통해 서로의 이슈를 확인하고 특정 사건을 확인합니다. 
  detail_url: #
  readmore_url: #

- background_url: images/team_project3.PNG
  animation: fadeInRight
  name: Mixtape Seoul(2022.03)
  description: 모방하여 팀 프로젝트를 진행하였으며 , 음악 제작을 위한 디지털 믹스테이프를 판매, 제공하는 아티스트 타겟 쇼핑몰 프로젝트 입니다.
  detail_url: #
  readmore_url: #

project_business_name: Business
project_business: # 형식에 맞추어 항목 추가
- background_url: images/my_business.PNG
  animation: fadeInTop
  name: 인프런강의(2021~)
  description: >-
    취준과 대학원진학을 동시에 했을때 많은 곳에서 github 주소뿐만아니라 개발 블로그주소도 요청하는데가 많았다.(물론 필수는 아니였지만) 
    또한 교육기관(멋쟁이사자처럼,네이버 부스트 캠프, 소마등)에서도 마찬가지이다. 현재 프로그래밍의 중요도가 올라가고있으며 초등학생부터 의무교육을 시작한다고 한다. 
    많은 비전공자들이 뒤늦게 프로그래밍을 시작하고 있다. 열심히 배우고 지원할려니 개발 블로그를 요청한다... 프로그래밍을 시작할때 알았다면 얼마나 좋았을까. 
    공부하면서 블로그 내용을 채웠으면 참 좋았을것이다. 이런 흐름을 캐치하여 나는 개발자다운 블로그인 깃헙블로그를 만드는 짧은 강의를 만들었다. 
  detail_url: #
  readmore_url: #


# Experience
exp_meta: What have I achieved?
exp_header: What I Experienced
exp_content: 기술력 외에도 이러한 역량을 겸비하고 있습니다. 
exp_services: # 형식에 맞추어 항목 추가
- name: 소통력 
  color: color-2
  icon: icon-speech-bubble
  content: 개발은 협업으로 이루어지기에 소통 또한 중요하다고 생각합니다. 활발한 성격으로 소통에 능합니다.
- name: 습득력
  color: color-2
  icon: icon-lightbulb
  content: 다방면으로 호기심이 많아 탐구하는 습관으로 새로운 것을 만났을 때 빠르게 습득합니다. 
- name: 자기계발 
  color: color-3
  icon: icon-book
  content: 자기계발에 관심이 많습니다. 독서를 통해 인사이트를 얻고 꾸준한 운동으로 체력을 다지고 있습니다.
exp_counters:
- name: project
  count: 3
  speed: 5000


# Career
carerr_meta: career
career_header: Work Career
career_list:
- name: 의정부 을지대학교병원    
  date: 2021.00 ~ 2022.00 
  content: 의정부,노원 을지대학교병원 운영 인프라팀<br> * 그룹웨어 전자결재 유형 수정및 개발<br> * 보안 관리 (사용자 website 접근& 프로그램 라이선스 허용/차단 , network IP 할당 및 관리)<br> * 로컬PC & 병원 솔루션 장비 관리 및 정비
  color: color-2
  icon: icon-pen2
  animation: fadeInLeft
- name: JLab Software
  date: 2023.08 ~ 2023.11
  content: 프로젝트 수행 및 커스터마이징 개발<br>프로젝트 기획자와 적극적으로 꾸준히 소통하여 기존에 있던 요구사항 개선 및 상향 경험             
  color: color-2
  icon: icon-pen2
  animation: fadeInLeft



# Education
edu_meta: Education
edu_header: Education
edu_list:
- title: UNIVERSITY
  subtitle: 서일대학교 전기과
  date: 2015.03 - 2016.02 (중퇴)
  content: 1년 재학 후 군 입대를 하였고, 전공(전기)이 나에게 맞지 않다고 판단하여 제대하고 자퇴하였습니다. 
- title:  HIGH SCHOOL
  subtitle: 의정부공업고등학교
  date: 2011.03 - 2014.02
- title:  Academy
  subtitle: 노원 그린컴퓨터 학원
  date: 2022.11 - 2023.05
  content: 자바와 Spring Boot를 활용한 웹 개발자 양성과정




# Blog
# blog_meta: self-improvement
# blog_header: BLOG and YOUTUBE
# blog_load_more: 더 발전하기 위해 항상 노력합니다    # 더보기 내용
# blog_load_more_url: #
# blog_list:
# - title: 깃허브 블로그 
#   subtitle: 개발 블로그 운영
#   date: 2021.11
#   content: 깃 블로그를 직접 개발하여 배운 것들을 꾸준히 기록하며 배움을 나눕니다. 
#   thumbnail_url: images/gitblog.png
#   link: https://hyesue-lee.github.io/
# - title: 유튜브 개발채널
#   subtitle: 개발 컨텐츠 유튜브 채널 운영 [치얼스헤나]
#   date: 2020.11
#   content: 유튜브 채널을 운영하며 같은 분야의 다양한 사람들과 소통하고 있습니다. 
#   thumbnail_url: images/youtube.png
#   link: https://youtube.com/channel/UC6YIWKSsY_J7rMYfAb7_tOw
# - title: 티스토리 블로그 
#   subtitle: 이전 블로그
#   date: 2018.03
#   content: 2018년부터 꾸준히 기록하였던 티스토리 첫 블로그 입니다. 
#   thumbnail_url: images/ti.png
#   link: https://cheershennah.tistory.com/


# Contact
contact_meta: Get in Touch
contact_header: Contact
contact_list:
- title: jccc23@naver.com
  icon: icon-globe-outline
- title: +82 10 5165 0048
  icon: icon-phone
- title: 경기도 의정부시
  icon: icon-map

contact_message: <em>연락해주셔서 감사합니다.</em> 24시간이내에 회신드리도록 하겠습니다. :)


optional_front_matter:
  remove_originals:    true
