title: jichang portfolio
name: JICHANG LEE
email: jccc23@naver.com
description: >-
  Web Developer & Java Backend 


baseurl: ""
url: "https://jichang-lee.github.io"


# profile 이미지
profile_image: images/profile1.png



# Custom Color
primary: 0B0719 #메인 폰트 컬러 
primary_hover: 44A4F2 #메인 버튼색 
color_1: CF94D8 #bar1
color_2: CF94D8 #bar2
color_3: CF94D8 #bar3
color_4: CF94D8 #bar4 
color_5: CF94D8
color_6: CF94D8



# About
about_meta: About Me
about_header: >- 
  "Just do it and take it"
#about_introduce: >-
  
about_content: >-
  🐣 <strong>안녕하세요. 과정에서 깨달음을 얻는것을 좋아하는 신입 백엔드 개발자, 이지창입니다.</strong> <br>
  다양한 것을 보고 경험하는 것을 좋아하고 새로움에 있어서 항상 재미와 흥미를 가지고 있습니다.<br>
  특정 무언가 할 때 ,같은 걸 반복하지 않고자 고민하는 성향이 있습니다. 코드를 작성할 때도
  <strong>3번 이상</strong> 반복되는 코드를 작성하지 않으려 생각하고 고민하는 개발자 입니다.<br>
  사람들과 소통하는 것을 좋아합니다. 새로운 환경에 있어서 사람들과 서로 흥미거리를 공유하고 친밀감을 가지려
  노력하는 편 입니다. 자연스럽게 대화가 유연해지고 개발자&비개발자 모두 원활하게 소통할 수 있도록 존중하는 마음가짐을 가지고 있습니다.

#about_services: # 형식에 맞추어 항목 추가
#- icon: icon-code
#  name: Java
#- icon: icon-data
#  name: DB
#- icon: icon-monitor
#  name: Web
#- icon: icon-phone3
#  name: App

##about_box_content: 괜찮은 문구 <br>박스 색바꾸는 yml파일에 추가 <br><br><br>야물파일로 변환 <strong>의뢰</strong>의뢰
##about_box_button:
##  link: #
##  name: sample


# Tech  skill
tech_meta: TECH SKILLS
tech_header: "The Skills that I can do"
tech_content: 저는 이런 것을 할 수 있습니다. 
#tech_list: # 형식에 맞추어 항목 추가
#- name: JAVA
#  color: color-1
#  animation: fadeInLeft
#  percent: 60
#  mark: 60
#  content: JAVA 기초와 객제 지향 언어의 기본적인 문법 & 자료구조 및 알고리즘을 자바로 공부하고있습니다.<br>
#- name: Spring Boot
#  color: color-2
#  animation: fadeInRight
#  percent: 60
#  mark: 60
#  content: Spring Boot 웹 프로젝트 경험으로 Spring의 전반적인 구조에 대해서 이해하고 있습니다.<br>
#- name: AWS
#  color: color-3
#  animation: fadeInLeft
#  percent: 20
#  mark: 20
#  content: AWS EC2를 사용하여 자동화 배포를 한 경험이 있습니다.
#- name: Github
#  color: color-4
#  animation: fadeInRight
#  percent: 30
#  mark: 30
#  content: 모든 프로젝트를 github를 통해 소스 코드를 관리하였습니다. 협업 당시에는 gitlab 를 사용하였고, 실제 서비스 배포할 때 merge request,PR 등 어떤 방식으로 반영하는지에 대한 구조를 습득하고 이해하였습니다.
tech_Bskill: Backend - JAVA , Spring Boot , Spring Data JPA + QueryDSL, MySQL
tech_Fskill: Frontend - javascript , Vue.js & nuxt3
#tech_Dskill: Dev - intelliJ , DataGrip, MySQL WorkBench, gitlab

# Project
#project_meta: My Work
#project_header: PROJECT
#project_introduce:
##project_load_more: 앞으로 더 많은 프로젝트가 추가될 예정입니다.    # 더보기 내용
#project_load_more_url: #
# project_my_name: 개인 프로젝트

# project_my: # 형식에 맞추어 항목 추가
# # - background_url: images/spring.png
# #   animation: fadeInLeft
# #   name: Spring WEB site
# #   description: Spring Framework를 활용한 웹사이트 제작 프로젝트 입니다.
# #   detail_url: #
# #   readmore_url: #

# - background_url: images/main1.jpg
#   animation: fadeInLeft
#   name: DEV blog
#   description: 준비중
#   detail_url: 
#   readmore_url: #

#project_team_name: 팀 프로젝트
#project_team: # 형식에 맞추어 항목 추가
#- background_url: images/groupware3.jpg
#  animation: fadeInRight
#  name: Groupware(2022.04)
#  description: 동네 지구대에서 쓸법한 프로젝트입니다.<br> 공지사항 및 캘린더를 통해 서로의 이슈를 확인하고 특정 사건을 확인합니다.
#  detail_url: https://github.com/jichang-lee/Groupware-Project
#
#- background_url: images/mixtape4.png
#  animation: fadeInRight
#  name: Mixtape Seoul(2022.03)
#  description: 모방하여 팀 프로젝트를 진행하였으며 , 음악 제작을 위한 디지털 믹스테이프를 판매, 제공하는 아티스트 타겟 쇼핑몰 프로젝트 입니다.
#  detail_url: https://github.com/jichang-lee/Mixtape-shopping

#project_business_name: Business
#project_business: # 형식에 맞추어 항목 추가
#- background_url: images/my_business.PNG
#  animation: fadeInTop
#  name: 인프런강의(2021~)
#  description: >-
#    취준과 대학원진학을 동시에 했을때 많은 곳에서 github 주소뿐만아니라 개발 블로그주소도 요청하는데가 많았다.(물론 필수는 아니였지만)
#    또한 교육기관(멋쟁이사자처럼,네이버 부스트 캠프, 소마등)에서도 마찬가지이다. 현재 프로그래밍의 중요도가 올라가고있으며 초등학생부터 의무교육을 시작한다고 한다.
#    많은 비전공자들이 뒤늦게 프로그래밍을 시작하고 있다. 열심히 배우고 지원할려니 개발 블로그를 요청한다... 프로그래밍을 시작할때 알았다면 얼마나 좋았을까.
#    공부하면서 블로그 내용을 채웠으면 참 좋았을것이다. 이런 흐름을 캐치하여 나는 개발자다운 블로그인 깃헙블로그를 만드는 짧은 강의를 만들었다.
#  detail_url: #
#  readmore_url: #


# Experience
exp_meta: What have I achieved?
exp_header: What I Experienced
exp_content: 기술력 외에도 이러한 역량을 겸비하고 있습니다. 
exp_services: # 형식에 맞추어 항목 추가
- name: 소통력 
  color: color-2
  icon: icon-speech-bubble
  content: 개발은 협업으로 이루어지기에 소통 또한 중요하다고 생각합니다. 활발한 성격으로 소통에 능합니다.
- name: 습득력
  color: color-2
  icon: icon-lightbulb
  content: 다방면으로 호기심이 많아, 새로운 것을 마주할 때 걱정보다는 흥미가 항상 앞서있습니다.
- name: 책임감 
  color: color-3
  icon: icon-book
  content: 맡은 일에 성실하게 처리하고 주어진 것에 대해 책임감을 갖고 임합니다.
exp_counters:
- name: project
  count: 3
  speed: 5000


# Career
carerr_meta: career
career_header: Work Career
career_list:
- name: 의정부 을지대학교병원    
  date: 2020.08 ~ 2022.08 
  content: 의정부,노원 을지대학교병원 운영 인프라팀<br> * 가상화 Virtual Machine 운영 관리자 <br> * 그룹웨어 전자결재 유형 수정및 개발<br> * 보안 관리 (사용자 website 접근& 프로그램 라이선스 허용/차단 , network IP 할당 및 관리)<br> * 로컬PC & 병원 솔루션 장비 관리 및 정비
  color: color-2
  icon: icon-pen2
  animation: fadeInLeft
- name: (주)제이랩
  date: 2023.08 ~ 2023.11 (인턴)
  content: 웹 프로젝트 수행 및 커스터마이징 개발 (Front)<br> * 글로벌 사업 확장으로 인한 신규 개발<br> * 주문상품,결제내역 조회, CS 1:1 문의 등  <br> <br>프로젝트 기획자와 적극적으로 꾸준히 소통하여 기존에 있던 요구사항 개선 경험
  color: color-2
  icon: icon-pen2
  animation: fadeInLeft
- name: (주)포유소프트
  date: 2024.02 ~ ing
  content: 모바일 앱 신규 프로젝트 (backend) <br> * 사업자 조회 페이지 크롤링하여 특정 회원 인증 기능 개발 <br> * 랭킹,뱃지부여 등 스케줄러 및 배치성 개발 <br> * 푸시 및 알림 기능 개발 <br> * 로직 및 쿼리 수정을 통해 서비스 성능 5.7s -> 2.3s 개선 경험
  color: color-2
  icon: icon-pen2
  animation: fadeInLeft




# Education
edu_meta: Education
edu_header: Education
edu_list:
- title: UNIVERSITY
  subtitle: 서일대학교 전기과
  date: 2015.03 - 2016.02 (중퇴)
  content: 1년 재학 후 군 입대를 하였고, 전공(전기)이 본인에게 맞지 않다고 판단하여 제대 후 자퇴하였습니다. 
- title:  HIGH SCHOOL
  subtitle: 의정부공업고등학교 <br>컴퓨터응용기계과
  date: 2011.03 - 2014.02
- title:  Academy
  subtitle: 노원 그린컴퓨터 학원
  date: 2022.11 - 2023.05
  content: JAVA와 Spring Boot를 활용한 웹 백엔드 개발자 양성과정




# Contact
contact_meta: Get in Touch
contact_header: Contact
contact_list:
- title: jccc23@naver.com
  icon: icon-globe-outline
- title: +82 10 5165 0048
  icon: icon-phone
- title: 경기도 의정부시 호원동
  icon: icon-map

#contact_message: <em>연락해주셔서 감사합니다.</em> 24시간이내에 회신드리도록 하겠습니다. :)


optional_front_matter:
  remove_originals:    true
